import { BrowserWindow, app, ipcMain, session } from 'electron';
import {
  ReadContentErrorIpcReceiveChannel,
  ReadContentIpcReceiveChannel,
  RequestReadIpcSendChannel,
  RequestWriteIpcSendChannel,
  WriteContentErrorIpcReceiveChannel,
  WriteContentIpcReceiveChannel
} from '../model/electronIpc';
import { injectCorsHeaders, isApicalApiUrl } from './electron/corsHeaders';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

import path from 'node:path';

const __dirname = path.dirname(__filename);

// import ('electron-squirrel-startup').catch(() => {
//   app.quit();
// });

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

const configureChromiumCacheDirectory = (): void => {
  const baseDir = process.env.LOCALAPPDATA || process.env.TEMP;
  if (!baseDir) {
    return;
  }
  const cacheDir = path.join(baseDir, 'RaceSweet', 'chromium-cache');
  app.commandLine.appendSwitch('disk-cache-dir', cacheDir);
};

configureChromiumCacheDirectory();

process.on('warning', (warning) => {
  const trace = warning.stack ?? `${warning.name}: ${warning.message}`;
  console.warn(trace);
});

const configureCorsForApicalRequests = (): void => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    if (isApicalApiUrl(details.url)) {
      callback({ responseHeaders: injectCorsHeaders(details.responseHeaders ?? {}) });
    } else {
      callback({ responseHeaders: details.responseHeaders });
    }
  });
};

const createWindow = (): void => {
  configureCorsForApicalRequests();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    width: 1024,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', (): void => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', (): void => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.on(RequestReadIpcSendChannel, (event: Electron.IpcMainEvent, filename: string, eventId: string, dataType?: string): void => {
  // const fs = require('fs');
  // const path = require('path');
  const filePath = path.join(__dirname, filename);
  
  readFile(filePath).then((data: Buffer) => {
    if (dataType === 'utf-8' || dataType === 'utf8') {
      const utf8Data = new TextDecoder('utf-8').decode(data);
      event.reply(ReadContentIpcReceiveChannel, eventId, utf8Data, 'utf-8');
    } else {
      event.reply(ReadContentIpcReceiveChannel, eventId, data);
    }
  }).catch((error: Error) => {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'ENOENT') {
      console.info(`Optional file not found at ${filePath}.`);
    } else if (nodeError.code === 'EACCES' || nodeError.code === 'EPERM') {
      console.warn(`Permission denied while reading ${filePath}.`);
    }
    else {
      // Handle unexpected file read errors.
      console.error(`Error reading file ${filename} within dir ${__dirname}`, error);
    }

    const errMsg = `Error reading file ${filename} within dir ${__dirname}`;
    error.message = errMsg + ': ' + error.message;
    event.reply(ReadContentErrorIpcReceiveChannel, eventId, error.message);
  });
  // event.reply('sendReadContent', filename, data);
});

ipcMain.on(RequestWriteIpcSendChannel, (event: Electron.IpcMainEvent, filename: string, eventId: string, contents: string) => {
  // Use __dirname if you're trying to restrict where things can be written to.
  // You need to handle permissions and security based on what you want to allow to be written.
  // I'd probably re-write this to take PathLike.
  const fullPath = path.join(__dirname, filename);
  const fullDirPath = path.dirname(fullPath);

  mkdir(fullDirPath, { recursive: true }).then(() => writeFile(fullPath, contents)).then(() => {
    event.returnValue = `File ${filename} written successfully.`;
    event.reply(WriteContentIpcReceiveChannel, eventId);
  }).catch((error: Error) => {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'EACCES' || nodeError.code === 'EPERM') {
      console.warn(`Permission denied while writing ${fullPath}.`);
    } else {
      console.error(`Failed to write file ${fullPath}`, error);
    }
    event.reply(WriteContentErrorIpcReceiveChannel, eventId, error.message);
  });
});
