import './runtimeSourceMaps.ts';

import { BrowserWindow, app, dialog, ipcMain, session, shell } from 'electron';
import { readFile } from 'node:fs/promises';
import {
  ReadContentErrorIpcReceiveChannel,
  ReadContentIpcReceiveChannel,
  RequestExternalHttpIpcInvokeChannel,
  RequestOpenLocalFileIpcInvokeChannel,
  RequestOpenExternalUrlIpcInvokeChannel,
  RequestReadIpcSendChannel,
  RequestSelectLocalDirectoryIpcInvokeChannel,
  RequestSelectLocalFileIpcInvokeChannel,
  RequestWriteIpcSendChannel,
  WriteContentErrorIpcReceiveChannel,
  WriteContentIpcReceiveChannel
} from '../model/electronIpc';
import { buildContentSecurityPolicy, injectContentSecurityPolicyHeader } from './contentSecurityPolicy';
import { injectCorsHeaders, isAllowedCorsDownloadUrl } from './electron/corsHeaders';
import { writeApplicationFile } from './fileWrite';
import type { FileWriteOptions } from './fileWriteDiagnostics';
import { waitForContentServer, waitForWindowContentLoad } from './startupContentServer';
import type { ExternalHttpProxyRequest, ExternalHttpProxyResponse, FileWriteDataType, SelectLocalFileOptions } from './window';

import path from 'node:path';
import { fetchExternalHttpProxy } from './externalHttpProxy';

export type IPCEventId = string;

const __dirname = path.dirname(__filename);

const resolveAppFilePath = (filename: string): string => {
  return path.isAbsolute(filename) ? filename : path.join(__dirname, filename);
};

// import ('electron-squirrel-startup').catch(() => {
//   app.quit();
// });

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

const configureChromiumCacheDirectory = (): void => {
  const baseDir = process.env.LOCALAPPDATA || process.env.TEMP;
  if (!baseDir) {
    return;
  }
  const cacheDir = path.join(baseDir, 'RaceSweet', 'chromium-cache');
  app.commandLine.appendSwitch('disk-cache-dir', cacheDir);
};

configureChromiumCacheDirectory();

process.on('warning', (warning) => {
  const trace = warning.stack ?? `${warning.name}: ${warning.message}`;
  console.warn(trace);
});

const configureSecurityHeaders = (): void => {
  const contentSecurityPolicy = buildContentSecurityPolicy();

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    let responseHeaders = details.responseHeaders ?? {};
    if (isAllowedCorsDownloadUrl(details.url)) {
      responseHeaders = injectCorsHeaders(responseHeaders);
    }

    if (details.resourceType === 'mainFrame') {
      responseHeaders = injectContentSecurityPolicyHeader(responseHeaders, contentSecurityPolicy);
    }

    callback({ responseHeaders });
  });
};

const showStartupError = (error: Error): void => {
  const detail = error.stack ?? error.message;

  console.error(`RaceSweet startup failed: ${detail}`);
  dialog.showErrorBox('RaceSweet startup failed', error.message);
};

const createWindow = async (): Promise<void> => {
  await waitForContentServer(MAIN_WINDOW_WEBPACK_ENTRY);

  configureSecurityHeaders();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    show: false,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    width: 1024,
  });

  await waitForWindowContentLoad(mainWindow, MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.show();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow().catch((error: Error) => {
    showStartupError(error);
    app.quit();
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', (): void => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', (): void => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow().catch((error: Error) => {
      showStartupError(error);
      app.quit();
    });
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.on(RequestReadIpcSendChannel, (event: Electron.IpcMainEvent, filename: string, eventId: IPCEventId, dataType?: string): void => {
  // const fs = require('fs');
  // const path = require('path');
  const filePath = resolveAppFilePath(filename);
  
  readFile(filePath).then((data: Buffer) => {
    if (dataType === 'utf-8' || dataType === 'utf8') {
      const utf8Data = new TextDecoder('utf-8').decode(data);
      event.reply(ReadContentIpcReceiveChannel, eventId, utf8Data, 'utf-8');
    } else {
      event.reply(ReadContentIpcReceiveChannel, eventId, data);
    }
  }).catch((error: Error) => {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'ENOENT') {
      console.info(`Optional file not found at ${filePath}.`);
    } else if (nodeError.code === 'EACCES' || nodeError.code === 'EPERM') {
      console.warn(`Permission denied while reading ${filePath}.`);
    } else {
      // Handle unexpected file read errors.
      console.error(`Error reading file ${filename} within dir ${__dirname}`, error);
    }

    const errMsg = `Error reading file ${filename} within dir ${__dirname}`;
    error.message = errMsg + ': ' + error.message;
    event.reply(ReadContentErrorIpcReceiveChannel, eventId, error.message);
  });
  // event.reply('sendReadContent', filename, data);
});

ipcMain.handle(RequestSelectLocalFileIpcInvokeChannel, async (event: Electron.IpcMainInvokeEvent, options?: SelectLocalFileOptions): Promise<string | undefined> => {
  const browserWindow = BrowserWindow.fromWebContents(event.sender);
  if (!browserWindow) {
    return undefined;
  }
  const result = await dialog.showOpenDialog(browserWindow, {
    filters: options?.filters,
    properties: options?.properties || ['openFile'],
    title: options?.title,
  });

  if (result.canceled) {
    return undefined;
  }

  return result.filePaths[0];
});

ipcMain.handle(RequestSelectLocalDirectoryIpcInvokeChannel, async (event: Electron.IpcMainInvokeEvent, title?: string): Promise<string | undefined> => {
  const browserWindow = BrowserWindow.fromWebContents(event.sender);
  if (!browserWindow) {
    return undefined;
  }
  const result = await dialog.showOpenDialog(browserWindow, {
    properties: ['openDirectory'],
    title,
  });

  if (result.canceled) {
    return undefined;
  }

  return result.filePaths[0];
});

ipcMain.handle(RequestExternalHttpIpcInvokeChannel, async (_event: Electron.IpcMainInvokeEvent, request: ExternalHttpProxyRequest): Promise<ExternalHttpProxyResponse> => {
  return fetchExternalHttpProxy(request);
});

ipcMain.handle(RequestOpenLocalFileIpcInvokeChannel, async (_event: Electron.IpcMainInvokeEvent, filename: string): Promise<void> => {
  const fullPath = resolveAppFilePath(filename);
  const errorMessage = await shell.openPath(fullPath);
  if (errorMessage) {
    throw new Error(errorMessage);
  }
});

ipcMain.on(RequestWriteIpcSendChannel, (
  event: Electron.IpcMainEvent,
  filename: string,
  eventId: IPCEventId,
  contents: string,
  dataType: FileWriteDataType = 'utf8',
  options?: FileWriteOptions,
): void => {
  void writeApplicationFile({ contents, dataType, filename, options }, {
    getUserDataPath: () => app.getPath('userData'),
    resolvePath: resolveAppFilePath,
  }).then(() => {
    event.reply(WriteContentIpcReceiveChannel, eventId);
  }).catch((error: unknown) => {
    event.reply(WriteContentErrorIpcReceiveChannel, eventId, error);
  });
});

ipcMain.handle(RequestOpenExternalUrlIpcInvokeChannel, async (_event: Electron.IpcMainInvokeEvent, urlText: string): Promise<void> => {
  const url = new URL(urlText);
  if (url.protocol !== 'https:') {
    throw new Error('Only HTTPS URLs may be opened externally.');
  }
  await shell.openExternal(url.toString());
});

ipcMain.handle('get-cookies', async (event, targetUrl) => {
  try {
    // This queries Chromium's inner cookie database directly
    const cookies = await session.defaultSession.cookies.get({ url: targetUrl });
    return cookies; 
  } catch (error) {
    console.error('Failed to get cookies:', error);
    return [];
  }
});
