import { BrowserWindow, app, ipcMain, session } from 'electron';
import {
  ReadContentErrorIpcReceiveChannel,
  ReadContentIpcReceiveChannel,
  RequestReadIpcSendChannel,
  RequestWriteIpcSendChannel,
  WriteContentErrorIpcReceiveChannel,
  WriteContentIpcReceiveChannel
} from '../model/electronIpc';
import { injectCorsHeaders, isApicalApiUrl } from './electron/corsHeaders';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createServer } from 'node:http';

import path from 'node:path';
import fs from 'node:fs';
import net from 'node:net';

const __dirname = path.dirname(__filename);

// import ('electron-squirrel-startup').catch(() => {
//   app.quit();
// });

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

const configureChromiumCacheDirectory = (): void => {
  const baseDir = process.env.LOCALAPPDATA || process.env.TEMP;
  if (!baseDir) {
    return;
  }
  const cacheDir = path.join(baseDir, 'RaceSweet', 'chromium-cache');
  app.commandLine.appendSwitch('disk-cache-dir', cacheDir);
};

configureChromiumCacheDirectory();

process.on('warning', (warning) => {
  const trace = warning.stack ?? `${warning.name}: ${warning.message}`;
  console.warn(trace);
});

const configureCorsForApicalRequests = (): void => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    if (isApicalApiUrl(details.url)) {
      callback({ responseHeaders: injectCorsHeaders(details.responseHeaders ?? {}) });
    } else {
      callback({ responseHeaders: details.responseHeaders });
    }
  });
};

// Create HTTP server for development
const createHttpServer = (): any => {
  const PORT = parseInt(process.env.DEBUG_SERVER_PORT || '3000', 10);
  const STATIC_FOLDER = path.join(__dirname, '..', 'public');
  const mimeTypes: Record<string, string> = {
    '.css': 'text/css',
    '.gif': 'image/gif',
    '.html': 'text/html',
    '.ico': 'image/x-icon',
    '.jpg': 'image/jpeg',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.svg': 'image/svg+xml',
  };

  const server = createServer((req: any, res: any) => {
    if (req.url) {
      const filePath = path.join(STATIC_FOLDER, req.url === '/' ? '../index.html' : req.url);
      fs.stat(filePath, (err: any, stats: any) => {
        if (err || !stats.isFile()) {
          res.writeHead(404, { 'Content-Type': 'text/plain' });
          console.error(`File not found: ${filePath}`, err);
          res.end('Not Found');
          return;
        }

        const ext = path.extname(filePath).toLowerCase();
        const contentType = mimeTypes[ext] || 'application/octet-stream';
        res.writeHead(200, { 'Content-Type': contentType });
        console.log(`Serving file: ${filePath}`);

        const readStream = fs.createReadStream(filePath);
        readStream.pipe(res);
      });
    } else {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Not Found');
    }
  });

  server.listen(PORT, (err: any) => {
    if (err) {
      // If port is in use, try next available port
      if (err.code === 'EADDRINUSE') {
        const nextPort = PORT + 1;
        console.log(`Port ${PORT} is in use, trying port ${nextPort}...`);
        if (nextPort > PORT + 10) {
          console.error(`Could not find available port after trying ports ${PORT} to ${nextPort}`);
          return;
        }
        server.listen(nextPort, () => {
          console.log(`Development server is running at http://localhost:${nextPort}`);
        });
      } else {
        console.error(`Failed to start server: ${err.message}`);
      }
    } else {
      console.log(`Development server is running at http://localhost:${PORT}`);
    }
  });

  return server;
};

const createWindow = (): void => {
  configureCorsForApicalRequests();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    width: 1024,
  });

  // Create and start HTTP server with auto-port detection
  const server = createHttpServer();
  
  // Get the actual port the server is listening on
  const actualPort = server.address().port;
  
  // Send the actual port to the renderer process
  mainWindow.webContents.send('actual-port', actualPort);
  
  // Load from HTTP server using the actual port
  mainWindow.loadURL(`http://localhost:${actualPort}`);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', (): void => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', (): void => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.on(RequestReadIpcSendChannel, (event: Electron.IpcMainEvent, filename: string, eventId: string, dataType?: string): void => {
  // const fs = require('fs');
  // const path = require('path');
  const filePath = path.join(__dirname, filename);
  
  readFile(filePath).then((data: Buffer) => {
    if (dataType === 'utf-8' || dataType === 'utf8') {
      const utf8Data = new TextDecoder('utf-8').decode(data);
      event.reply(ReadContentIpcReceiveChannel, eventId, utf8Data, 'utf-8');
    } else {
      event.reply(ReadContentIpcReceiveChannel, eventId, data);
    }
  }).catch((error: Error) => {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'ENOENT') {
      console.info(`Optional file not found at ${filePath}.`);
    } else if (nodeError.code === 'EACCES' || nodeError.code === 'EPERM') {
      console.warn(`Permission denied while reading ${filePath}.`);
    }
    else {
      // Handle unexpected file read errors.
      console.error(`Error reading file ${filename} within dir ${__dirname}`, error);
    }

    const errMsg = `Error reading file ${filename} within dir ${__dirname}`;
    error.message = errMsg + ': ' + error.message;
    event.reply(ReadContentErrorIpcReceiveChannel, eventId, error.message);
  });
  // event.reply('sendReadContent', filename, data);
});

ipcMain.on(RequestWriteIpcSendChannel, (event: Electron.IpcMainEvent, filename: string, eventId: string, contents: string) => {
  // Use __dirname if you're trying to restrict where things can be written to.
  // You need to handle permissions and security based on what you want to allow to be written.
  // I'd probably re-write this to take PathLike.
  const fullPath = path.join(__dirname, filename);
  const fullDirPath = path.dirname(fullPath);

  mkdir(fullDirPath, { recursive: true }).then(() => writeFile(fullPath, contents)).then(() => {
    event.returnValue = `File ${filename} written successfully.`;
    event.reply(WriteContentIpcReceiveChannel, eventId);
  }).catch((error: Error) => {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'EACCES' || nodeError.code === 'EPERM') {
      console.warn(`Permission denied while writing ${fullPath}.`);
    } else {
      console.error(`Failed to write file ${fullPath}`, error);
    }
    event.reply(WriteContentErrorIpcReceiveChannel, eventId, error.message);
  });
});
